package com.bfarming.constants;
public enum AppCodes {
    NOT_AUTHORISED(1000), VALIDATION(1002), UNSUPPORTED_MEDIA_TYPE(1003), ENTITY_NOT_FOUND(
            1004), INVALID_PAGE_NOS(1005), INVALID_USER_ID(1006), INVALID_SUGGEST_TYPE(
            1007), INVALID_SUGGEST_MIN_CHARS(1008), NO_ARTICLE_FOUND(
            1009), UPDATE_RATE_FAILED(1010), ARTICLE_UPDATE_FAILED(1011),  INVALID_DATE(1013), STARTDATE_GREATER_THAN_ENDDATE(
            1014), UNKNOWN_ERROR(1021),
    INVALID_ARTICLE_TYPE(1022), NOT_NULL(1023) , COMPLETE_CACHE_REFRESH_FAILED(1024),
    CITY_CACHE_REFRESH_FAILED(1025) ,SERVICE_CACHE_REFRESH_FAILED(1026), CREATE_ARTICLE_FAILED(1027);

    private Integer code;

    AppCodes(Integer code) {
        this.code = code;
    }

    public Integer getCode() {
        return code;
    }



}

